### ISSUE TITLE
Add the automatic installation of dependencies to the installation script

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [ElectricRCAircraftGuy/PDF2SearchablePDF#31]
...such as tesseract and whatever.

Installation script: https://github.com/ElectricRCAircraftGuy/PDF2SearchablePDF/blob/master/install.sh

**Comment by florisre** [comment]
this would need to recognize the operating system the script is running on, am I right? Since currently it runs well on arch based distros, this might be a breaking change if implemented. Same for Mac OS X.

**Comment by ElectricRCAircraftGuy** [comment]
@florisre , yeah, you're right. If I start adding `sudo apt install whatever` lines into the script it will only work on Ubuntu. I'll keep that in mind and add a mechanism to catch it, maybe only automatically installing dependencies if `lsb_release -d` indicates the Linux distro is Ubuntu.

**Comment by ElectricRCAircraftGuy** [comment]
@florisre , I've updated the installation script to automatically install dependencies for Ubuntu only. Please test it and let me know if it works for you. (meaning: it doesn't break anything for you)
