### ISSUE TITLE
pdf2searchablepdf: command not found

### ISSUE THREAD

**Issue by eliyaz-virtech** [ElectricRCAircraftGuy/PDF2SearchablePDF#4]
after running `sudo ./install.sh`, i tried to run `pdf2searchablepdf ./test_pdfs/test1.pdf` but its showing 

> error pdf2searchablepdf: command not found

i see that there is no dir created "pdf2searchablepdf" in bin folder

**Comment by ElectricRCAircraftGuy** [comment]
What do you get when you type `ls -al ~/bin`?
You should see the `pdf2searchablepdf` file pointing to your installation location (where you unzipped the main directory).

How about `echo $PATH | grep "/home/$USER/bin"`?
You should see that `/home/YOUR_USERNAME/bin` is part of the path.

**Comment by ElectricRCAircraftGuy** [comment]
Is your problem solved? If so, please post your answer and how you fixed it, to help the next person, and close this issue.

**Comment by eliyaz-virtech** [comment]
It resolved thank you,

`ls -al ~/bin `-> /home/user_name/workspace/PDF2SearchablePDF/pdf2searchablepdf.sh

`echo $PATH | grep "/home/$USER/bin" ` -> bin:/home/user_name/bin

**Comment by bcnero** [comment]
Hello!

I have got the same error: error pdf2searchablepdf: command not found

On this commands i get:

ls -al ~/bin:   pdf2searchablepdf -> /home/my_user_name/Downloads/PDF2SearchablePDF/pdf2searchablepdf.sh

echo $PATH | grep "/home/$USER/bin":     no result...

I am using: lsb_release -a

best regards thomas

**Comment by ElectricRCAircraftGuy** [comment]
I'm assuming you ran the `install.sh` script?

If so, you need to:

1. **log out and log back in** if that script just created your `~/bin` dir (if `ls ~/bin` shows only the one `pdf2searchablepdf` symlink in that dir, and nothing else, then this is likely the case).
2. ensure you **do NOT delete the PDF2SearchablePDF repository you downloaded**, as the install script didn't copy the executable out of it, it created an executable symlink *to* it.

**Comment by bcnero** [comment]
Hi!

Thanks, "log out and log back in" was the problem, this machine is running 24/7 ... now it works great!!!!

Just out of interest, if I have to uninstall the tool, how do I proceed?

BEST regards from Cologne

**Comment by ElectricRCAircraftGuy** [comment]
@bcnero , [Cologne, Germany?](https://www.google.com/maps/place/Cologne,+Germany/@51.0252233,6.0286511,7z/data=!4m5!3m4!1s0x47bf259169ab2fe5:0x42760fc4a2a77f0!8m2!3d50.937531!4d6.9602786) 

**To uninstall:**

```bash
# 1. delete the symlink in ~/bin
rm ~/bin/pdf2searchablepdf
# 2. (Optional) delete the entire PDF2SearchablePDF repository directory, and all contents
# in it. WARNING! CHOOSING THE WRONG PATH HERE WILL erase everything in the folder you specify!
rm -rf path/to/PDF2SearchablePDF
```

**Comment by ElectricRCAircraftGuy** [comment]
I've updated the install instructions in the readme, and added uninstall instructions too.

**Comment by bcnero** [comment]
Thanks, great job!

@ElectricRCAircraftGuy:  "Cologne, Germany" => Yes, near Cologne :-) 50.54232418379376, 7.0950073037577255

... I think for Americans everything under 100km is the direct neighbor :-)
