### ISSUE TITLE
Thanks for sharing, very useful.

### ISSUE THREAD

**Issue by michaelsjackson** [ElectricRCAircraftGuy/PDF2SearchablePDF#7]
Tried quickly with pdf documents and it seems to work nicely. I was using gImageReader in ubuntu 18.04, which is great, now I wanted to do same, but from command line, meaning resaving as new pdf with searchable text and your tool is doing that perfectly.

I also like it is a bash solution, so one could finetune or replace components if wanted in future. Thanks a lot.

**Comment by ElectricRCAircraftGuy** [comment]
Hey, thanks! Glad you like it! How'd you find it, by the way? Be sure to give it a star here on Github to make it easier to find later if you like.

**Comment by michaelsjackson** [comment]
I found it via some discussion in those common it question answer sites. You got the star, not sure about the star system, how many stars can I give per month? Unlimited?

**Comment by michaelsjackson** [comment]
Regarding finetuning, I have recognized the added "text layer" is not readable when selected in pdf document, in gImageReader there was not this "problem", might the option hOCR output help here, not sure what is causing this effect.

**Comment by ElectricRCAircraftGuy** [comment]
> Regarding finetuning, I have recognized the added "text layer" is not readable when selected in pdf document, in gImageReader there was not this "problem", might the option hOCR output help here, not sure what is causing this effect.

I'm not sure what you mean here. Can you post some screenshots of what you expect to see vs what you do see?

**Comment by michaelsjackson** [comment]
When I open a _searchable pdf in evince in ubuntu 18.04, then marking some text, (which was added later by your script) I see only overlayed white rectangles per character, and not the character itself, thus I can not read it anymore, which is no big problem, but it would be nicer if we could continue the text, also in selected form. Maybe this is an evince only problem?   I can add screenshots later.

**Comment by michaelsjackson** [comment]
Here the screenshot, with selected text in evince in ubuntu 18.04, in any _searchable.pdf

![999(001)](https://user-images.githubusercontent.com/5049512/90309532-abd79500-dee9-11ea-8a16-8378ef1a34a9.png)

**Comment by michaelsjackson** [comment]
I guess using the hOCR option in tesseract might help.

**Comment by ElectricRCAircraftGuy** [comment]
Let's continue the conversation here: https://github.com/ElectricRCAircraftGuy/PDF2SearchablePDF/issues/8.
